### ISSUE TITLE
Instruction Images

### ISSUE THREAD

**Issue by rwieruch** [TOA-Berlin-TicTacToe/toa-tic-tac-toe-starter-kit#1]
![artboard copy 2 2x](https://user-images.githubusercontent.com/2479967/28008675-cff9e70c-6558-11e7-8434-cd339d96f6b0.jpg)
![artboard copy 3 2x](https://user-images.githubusercontent.com/2479967/28008676-d018bc40-6558-11e7-91e0-9090dcae428b.jpg)
![artboard copy 4 2x](https://user-images.githubusercontent.com/2479967/28008677-d023a498-6558-11e7-8a30-745576e7d96a.jpg)
![artboard copy 2x](https://user-images.githubusercontent.com/2479967/28008678-d023fb46-6558-11e7-889e-0672058969b7.jpg)
![artboard 2x](https://user-images.githubusercontent.com/2479967/28008679-d0297328-6558-11e7-956f-b2e340e7d19f.jpg)

**Comment by jotaen** [comment]
neat ❤️
